# Generated by Django 5.2.1 on 2025-05-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('AM', 'Allievi Maschi'), ('AF', 'Allieve Femmine'), ('JR', 'Juniores'), ('PM', 'Promesse'), ('SM', 'Senior'), ('SM35', 'Senior 35')], max_length=10)),
                ('stato', models.CharField(max_length=20)),
                ('specialita', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('luogo', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('data_nascita', models.DateField()),
                ('sesso', models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_persona', models.CharField(choices=[('presidente', 'Presidente'), ('allenatore', 'Allenatore'), ('fisioterapista', 'Fisioterapista'), ('atleta', 'Atleta')], max_length=20)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Specialita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartecipaGara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_prestazione', models.FloatField(blank=True, null=True)),
                ('punti', models.IntegerField(blank=True, null=True)),
                ('posizione', models.IntegerField(blank=True, null=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackApp.atleta')),
                ('gara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackApp.gara')),
            ],
        ),
        migrations.CreateModel(
            name='Fisioterapista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specializzazione', models.CharField(max_length=100)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trackApp.persona')),
            ],
        ),
        migrations.AddField(
            model_name='atleta',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trackApp.persona'),
        ),
        migrations.CreateModel(
            name='Allenatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trackApp.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Presidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trackApp.persona')),
            ],
        ),
        migrations.AddField(
            model_name='gara',
            name='specialita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trackApp.specialita'),
        ),
        migrations.CreateModel(
            name='Squadra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_squadra', models.CharField(max_length=50)),
                ('presidente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trackApp.presidente')),
            ],
        ),
        migrations.AddField(
            model_name='atleta',
            name='id_squadra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trackApp.squadra'),
        ),
    ]
