# Generated by Django 5.2.1 on 2025-05-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(max_length=254, unique=True, default='temp@email.com'),
            preserve_default=False,
        ),
    ]
